Manage git versions and conflicts
AlZorba/iDig-Webapp pull request #139
Opened 2024-05-26 12:08 UTC by AlZorba

**Issue** :  `https://github.com/esag-swiss/iDig-Webapp/issues/138`

**Description** :    
The PR implement a new module (thePatches) to manage sync when data version on server is newer than the client.

2024-05-27 15:56 UTC, dev-francois requested changes
Tiens, code review de fin journée, donc ça rale haha :D

2024-05-27 15:56 UTC, dev-francois commented on src/components/TheItem.vue
> +      }
Oh un peu vbizarre ça, il me semble que la gestion des retours d'api, ainsi que la gestion des localstorage est normalement fait hors des composants, dans le store ou apiclient ou autre. Là ça melange un peu tout si je ne me trompe

2024-05-27 15:56 UTC, dev-francois commented on .eslintrc.cjs
> +    // "vue/attribute-hyphenation": ["error", "never"],
Ah bon? Pourquoi? il s'agit de ça:
https://eslint.vuejs.org/rules/attribute-hyphenation
Normalement ça doit just fixer un type unique pour les props. A priori je deconseille de le desactiver, ça veut dire que differentes syntaxes sont possibles, et quand tu fais des recherches dans tous le projet, tu ne trouves jamais ce que tu cherches (ou seulement une partie). Franchement, si c'est juste qu'une prop n'etait pas reconnu, renomme la prop plutôt :)

2024-05-27 15:56 UTC, dev-francois commented on src/components/TheItem.vue
> +  scrollbar-width: none; /* Firefox */
C'est pourquoi? ça bloque le scrolling sur firefox? Ca peut être plus genant qu'autre chose, non? Et aussi, c'est un fix qui est encore necessaire de nos jours?

2024-05-27 15:56 UTC, dev-francois commented on src/components/ThePatches.vue
> +</style>
ok, je sais pas trop ce que ça fait. Ca a l'air d'un composant qui fait pas mal de logique, à voir si tu veux laisser la logique là, je peux pas dire.

2024-05-27 16:44 UTC, AlZorba commented on src/components/TheItem.vue
> +      }
en effet, je bosse sur la prochaine PR avec une séparation claire en introduisant ce que tu évoquais, sorte de API nettoyée. J'appelle ça un Api midleware. Ca joue?

2024-05-27 16:45 UTC, AlZorba commented on .eslintrc.cjs
> +    // "vue/attribute-hyphenation": ["error", "never"],
La moitié des props Quasar sont avec hyphenation ! je vérifie la best pratice.

2024-05-27 16:48 UTC, AlZorba commented on src/components/TheItem.vue
> +  scrollbar-width: none; /* Firefox */
c'est pour ne pas afficher la barre de défilement, je vérifie...

2024-05-27 16:48 UTC, AlZorba commented on src/components/TheItem.vue
> +  scrollbar-width: none; /* Firefox */
idem, cache la barre de défilement

2024-05-27 16:49 UTC, AlZorba commented on src/components/ThePatches.vue
> +</style>
Merci pour la review super réactive !

2024-05-27 16:49 UTC, AlZorba commented
Merci pour la review super réactive !

2024-05-27 17:11 UTC, AlZorba commented on src/components/ThePatches.vue
> +</style>
bon ca à l'air courant : https://www.w3schools.com/howto/howto_css_hide_scrollbars.asp

2024-05-28 15:47 UTC, dev-francois commented on .eslintrc.cjs
> +    // "vue/attribute-hyphenation": ["error", "never"],
ah alors je vois que `"always" (default) ... Use hyphenated name.`
Bon quasar suit les bonne pratiques, et le projet non.. zut.
On utilise tres tres peu de props je crois, grâce au store.
Et si tu met ` "vue/attribute-hyphenation": ["error", "always"],` et tu ouvres tous les composants, ça fait quoi? Il y a peut etre tres peu d'erreurs à corriger?

2024-05-28 15:47 UTC, dev-francois commented on src/components/TheItem.vue
> +  scrollbar-width: none; /* Firefox */
ok, si c'est voulu, ça roule!

2024-05-28 15:50 UTC, francoiscrouzet commented on src/components/ThePatches.vue
> +</style>
ah ok, attends, je parlais de tout le composant ici. Il à l'air de faire un peu tout

Sinon pour la scrollbar, comme dit, si c'est voulu, alors c'est bon. Si tu es sûr que tu n'as pas de content qui depassera et qui ne sera donc pas scrollable et donc pas visible

2024-05-29 11:57 UTC, dev-francois commented on .eslintrc.cjs
> +    // "vue/attribute-hyphenation": ["error", "never"],
@AlZorba ah attends!
Perso je trouve ["error", "never"] bien meilleur que "always". Enfin on peut en discuter.
Et je crois que les 2 sont compatibles de toutes façons. A mon avis, tu peut tout simplement garder l'actuel ["error", "never"] et passer les props quasar en camelCase. Donc si dans les exemples ou docs quasar il y a ecrit `a-quasar-prop`, tu pourrais tous simplement ecrire `aQuasarProp`

2024-07-29 10:58 UTC, AlZorba reviewed
A remettre en ordre et commenter lors des prochaines PR !

2024-07-31 12:01 UTC, dev-francois commented
> A remettre en ordre et commenter lors des prochaines PR !

Hey, ok, tu vas peut-être t'y perdre lors de la reprise? Si oui, une solution serait de faire une nouvelle PR avec les commits dont tu es sûr. Utiliser le systeme des cherry pick. Puis une PR avec les choses pas finalisées. Si c'est interressant pour toi, je peux te montrer

2024-08-01 07:54 UTC, AlZorba commented
Ah oui si tu peux m'expliquer ou me montrer !

2024-08-01 08:07 UTC, AlZorba commented
Si je retire le dernier commit, ca pourrait le faire en faite!?

2024-08-02 10:14 UTC, AlZorba reviewed
C'est déjà plus propre  !

2024-08-19 07:30 UTC, AlZorba commented
Hello, je ne vois pas les autres changements à faire pour pouvoir 'merger' !

2024-08-19 13:08 UTC, AlZorba reviewed
is it ok ?

2024-08-28 12:43 UTC, dev-francois approved these changes

2024-08-28 14:03 UTC, merged