Create a "isLoaded" state with its logic, and remove test data
AlZorba/iDig-Webapp pull request #27
Opened 2023-04-11 08:57 UTC by francoiscrouzet

**Issue** :  `https://github.com/archaiodata/thacer/issues/26`

**Description** :    
Create a "isLoaded" state with its logic, and remove test data
Instead of displaying test data at loading, we display a message asking the user to connect.
This allow to simplify the logic, and remove some test data

2023-04-11 08:58 UTC, francoiscrouzet commented
@AlZorba 
Attention, ça casse le mode "old_server", car on n'a pas la liste des trenches. Je ne me rappelle plus ce qu'on a dit vendredi, si c'est ok temporairement d'avoir seulement une des 2 solutions. Si pas ok, alors pas merger ;)

2023-04-12 12:24 UTC, francoiscrouzet commented
> Member

@AlZorba Fixed in last commit

2023-04-13 11:10 UTC, AlZorba commented on src/App.vue
> +          Veuillez sélectionner une ou plusieurs tranches
```suggestion
          Veuillez sélectionner au moins un secteur
```

2023-04-13 11:10 UTC, AlZorba reviewed
Testé, juste une modif

2023-04-13 11:13 UTC, AlZorba requested changes
trenches in English but in French secteur (or sondage but in the menu we have secteurs)

2023-04-13 18:46 UTC, francoiscrouzet commented
@AlZorba c'est fait, cool, je savais pas qu'on pouvait faire des suggestions ici, et les merger direct !
Je te laisse verifier, et on est bon !

2023-04-16 19:03 UTC, AlZorba approved these changes

2023-04-16 19:03 UTC, merged